name: build-and-test
on:
  push:
    branches:
      - main
      - develop
    paths:
      - include/**
      - silcondb/**
      - test/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - include/**
      - silicondb/**
      - test/**
jobs:
  build-and-test-using-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: mkdir build && cd build && cmake .. && make && ctest
