name: doxygen-docs
on:
  push:
    branches:
      - main
      - init/doc
jobs:
  generate-doxygen-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Download doxygen sources
        run: wget https://doxygen.nl/files/doxygen-1.9.3.src.tar.gz
      
      - name: Build doxygen
        run: |
          tar xzf doxygen-1.9.3.src.tar.gz
          cd doxygen-1.9.3
          mkdir build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -Wno-dev ..
          make && sudo make install
          cd .. && rm -rf doxygen-1.9.3

      - name: Build documentation
        run: cd docs && doxygen

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/html
