name: doxygen-docs
on:
  push:
    branches:
      - main
      - init/doc
jobs:
  generate-doxygen-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Download doxygen binaries
        run: wget https://webwerks.dl.sourceforge.net/project/doxygen/rel-1.9.1/doxygen-1.9.1.linux.bin.tar.gz
      
      - name: Extract archive
        run: tar xzf doxygen-1.9.1.linux.bin.tar.gz
      
      - name: Install doxygen
        run: cd doxygen-1.9.1 && ./configure --prefix /usr/bin && sudo make install 

      - name: Build documentation
        run: cd docs && doxygen

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/html
