name: doxygen-docs
on:
  push:
    branches:
      - main
      - init/doc
jobs:
  generate-doxygen-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Download doxygen sources
        run: wget https://doxygen.nl/files/doxygen-1.9.1.src.tar.gz
      
      - name: Build doxygen
        run: mkdir doxy-build && cd doxy-build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/ -Wno-dev .. && make && sudo make install

      - name: Build documentation
        run: cd docs && doxygen

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/html
